import type { ReactNode } from "react";
import { FiActivity, FiArrowUpRight, FiChevronDown, FiPackage, FiShoppingBag, FiTag, FiTrendingUp, FiUsers } from "react-icons/fi";
import type { Category } from "../../categories/types";
import type { Product } from "../../products/types";

const revenueBars = [42, 57, 48, 76, 62, 87, 72, 96, 79, 88, 68, 82];
const days = ["01", "05", "10", "15", "20", "25", "30"];

export function DashboardMetrics({ totalStock, loading }: { totalStock: number; loading: boolean }) {
    return <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Doanh thu tháng này" value="$48,290" trend="18.4%" icon={<FiTrendingUp />} accent="orange" /><MetricCard label="Đơn hàng mới" value="1,284" trend="12.8%" icon={<FiShoppingBag />} accent="mint" /><MetricCard label="Khách hàng" value="8,642" trend="8.2%" icon={<FiUsers />} accent="blue" /><MetricCard label="Sản phẩm trong kho" value={loading ? "..." : totalStock.toLocaleString("vi-VN")} trend="6.5%" icon={<FiPackage />} accent="violet" /></section>;
}

export function RevenueOverview() {
    return <div className="rounded-3xl border border-[#e3e3dc] bg-white p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-[#858b87]">Tổng quan doanh thu</p><div className="mt-2 flex items-baseline gap-3"><h2 className="text-3xl font-semibold tracking-[-0.06em]">$128,430</h2><span className="inline-flex items-center gap-1 text-sm font-semibold text-[#3c8b72]"><FiArrowUpRight /> 14.8%</span></div></div><button type="button" className="inline-flex items-center gap-2 rounded-lg border border-[#e4e4de] px-3 py-2 text-sm font-medium">30 ngày <FiChevronDown /></button></div><div className="mt-8 flex h-56 items-end gap-2 border-b border-[#ecece7] px-1 sm:gap-3">{revenueBars.map((height, index) => <div key={index} className="group relative flex h-full flex-1 items-end"><div className={`w-full rounded-t-md transition-all group-hover:bg-[#d95d39] ${index === 7 ? "bg-[#d95d39]" : "bg-[#dbe8df]"}`} style={{ height: `${height}%` }} /></div>)}</div><div className="mt-3 flex justify-between px-1 text-xs text-[#9b9f9b]">{days.map((day) => <span key={day}>{day} Sep</span>)}</div></div>;
}

export function StockAlert({ products }: { products: Product[] }) {
    const lowStockProducts = products.filter((product) => product.variants.reduce((sum, item) => sum + item.stockQuantity, 0) < 12);
    const fallback = [{ name: "Áo Linen cổ mở", stock: 4 }, { name: "Quần denim relaxed", stock: 7 }, { name: "Túi da mini", stock: 9 }];
    const rows = lowStockProducts.length ? lowStockProducts.slice(0, 3).map((product) => ({ name: product.name, stock: product.variants.reduce((sum, item) => sum + item.stockQuantity, 0) })) : fallback;
    return <div className="rounded-3xl border border-[#e3e3dc] bg-[#dcebe2] p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-[#567064]">Cần chú ý</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.06em]">{lowStockProducts.length || 3}</h2><p className="mt-1 text-sm text-[#567064]">sản phẩm sắp hết hàng</p></div><span className="rounded-xl bg-white/70 p-3 text-[#3c8b72]"><FiActivity className="text-xl" /></span></div><div className="mt-8 space-y-4">{rows.map((product) => <div key={product.name} className="flex items-center justify-between border-b border-[#bfd4c7] pb-3"><div className="flex min-w-0 items-center gap-3"><span className="h-2 w-2 rounded-full bg-[#d95d39]" /><span className="truncate text-sm font-semibold text-[#334d41]">{product.name}</span></div><span className="text-xs font-medium text-[#567064]">{product.stock} còn lại</span></div>)}</div><button type="button" className="mt-7 text-sm font-semibold text-[#334d41] underline decoration-[#9bbdad] underline-offset-4">Xem kho hàng <FiArrowUpRight className="inline" /></button></div>;
}

export function RecentProducts({ products, loading }: { products: Product[]; loading: boolean }) {
    return <div className="overflow-hidden rounded-3xl border border-[#e3e3dc] bg-white"><div className="flex items-center justify-between border-b border-[#ecece7] px-5 py-5 sm:px-7"><div><h2 className="font-semibold">Sản phẩm mới cập nhật</h2><p className="mt-1 text-sm text-[#858b87]">Theo dõi danh mục đang bán</p></div><button type="button" className="text-sm font-semibold text-[#d95d39]">Xem tất cả <FiArrowUpRight className="inline" /></button></div><div className="overflow-x-auto"><table className="w-full min-w-150 text-left text-sm"><thead className="bg-[#fafaf8] text-xs uppercase tracking-[0.12em] text-[#9b9f9b]"><tr><th className="px-5 py-3 font-medium sm:px-7">Sản phẩm</th><th className="px-4 py-3 font-medium">Danh mục</th><th className="px-4 py-3 font-medium">Giá</th><th className="px-4 py-3 font-medium">Tồn kho</th></tr></thead><tbody>{products.slice(0, 5).map((product) => { const stock = product.variants.reduce((sum, item) => sum + item.stockQuantity, 0); return <tr key={product.id} className="border-t border-[#f0f0eb]"><td className="px-5 py-4 font-semibold sm:px-7">{product.name}</td><td className="px-4 py-4 text-[#858b87]">{product.categoryName || "Chưa phân loại"}</td><td className="px-4 py-4 font-medium">${product.price.toFixed(2)}</td><td className="px-4 py-4"><span className={stock < 12 ? "text-[#d95d39]" : "text-[#3c8b72]"}>{stock || "-"} chiếc</span></td></tr>; })}{!products.length ? <tr><td colSpan={4} className="px-7 py-8 text-center text-sm text-[#858b87]">{loading ? "Đang tải dữ liệu..." : "Chưa có dữ liệu sản phẩm"}</td></tr> : null}</tbody></table></div></div>;
}

export function CategoryDistribution({ categories }: { categories: Category[] }) {
    const percentages = [42, 31, 18, 9];
    return <div className="rounded-3xl border border-[#e3e3dc] bg-[#191b1b] p-5 text-white sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm text-[#8d9692]">Phân bổ danh mục</p><h2 className="mt-2 text-2xl font-semibold">{categories.length} danh mục</h2></div><FiTag className="text-[#e9a86a]" /></div><div className="mt-8 space-y-5">{categories.slice(0, 4).map((category, index) => <div key={category.id}><div className="mb-2 flex justify-between text-sm"><span className="text-[#d8dedb]">{category.name}</span><span className="text-[#8d9692]">{percentages[index]}%</span></div><div className="h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-[#e9a86a]" style={{ width: `${percentages[index]}%` }} /></div></div>)}{!categories.length ? <p className="text-sm text-[#8d9692]">Đang chờ dữ liệu danh mục...</p> : null}</div></div>;
}

function MetricCard({ label, value, trend, icon, accent }: { label: string; value: string; trend: string; icon: ReactNode; accent: "orange" | "mint" | "blue" | "violet" }) {
    const accents = { orange: "bg-[#f7e1d4] text-[#c95a38]", mint: "bg-[#dcebe2] text-[#3c8b72]", blue: "bg-[#dce5f0] text-[#56759a]", violet: "bg-[#e6e1ee] text-[#806b9b]" };
    return <article className="rounded-[1.25rem] border border-[#e3e3dc] bg-white p-5"><div className="flex items-start justify-between"><p className="text-sm text-[#858b87]">{label}</p><span className={`rounded-xl p-2.5 ${accents[accent]}`}>{icon}</span></div><div className="mt-5 flex items-end justify-between gap-2"><strong className="text-2xl font-semibold tracking-[-0.06em]">{value}</strong><span className="mb-0.5 inline-flex items-center gap-1 text-xs font-semibold text-[#3c8b72]"><FiArrowUpRight /> {trend}</span></div></article>;
}